public static Audit createMockAudit() {
        Audit audit = new Audit();
        audit.setAuditId("12345");
        audit.setAuditDate("2023-05-22");
        audit.setAuditType("Type A");
        audit.setRacfId("racf123");
        audit.setUserGroup("Group A");
        audit.setExternalOrderId("Order123");
        audit.setDate(new Date());
        audit.setBusinessArea("Area A");
        audit.setBusinessAreaUserId("user123");
        audit.setIsCentralPrintSuccess("Yes");
        audit.setIsLocalPrintSuccess("Yes");
        audit.setIsArchivalSuccess("Yes");
        audit.setTemplateId("Template123");
        audit.setTeamName("Team A");
        audit.setCentreName("Centre A");
        audit.setAccountNo("Account123");
        audit.setTouchPointName("Touchpoint A");
        audit.setTouchPointGuid("Guid123");
        audit.setEnvironemntName("Environment A");
        audit.setSortcode("123456");
        audit.setBrand("Brand A");
        audit.setSubBrand("Sub Brand A");
        audit.setThirdPartyTemplate("Third Party Template");
        audit.setAddresseeLine1("Address Line 1");
        audit.setAddresseeLine2("Address Line 2");
        audit.setAddressLine1("Address Line 1");
        audit.setAddressLine2("Address Line 2");
        audit.setAddressLine3("Address Line 3");
        audit.setAddressLine4("Address Line 4");
        audit.setAddressLine5("Address Line 5");
        audit.setPostCode("12345");
        audit.setPhoneNumberRBS("1234567890");
        audit.setPhoneNumberNWB("9876543210");
        audit.setPhoneNumberUBN("0123456789");
        audit.setLotCodeRbs("Lot Code RBS");
        audit.setLotCodeNwb("Lot Code NWB");
        audit.setLotCodeUbn("Lot Code UBN");
        audit.setOverseasNumberRBS("987654321");
        audit.setOverseasNumberNWB("123456789");
        audit.setOverseasNumberUBN("012345678");
        audit.setBreCode("BRE123");
        audit.setBreDescription("BRE Description");
        audit.setSignatory("John Doe");
        audit.setSignatoryJobTitle("Manager");
        audit.setSignatorySignature("Signature123");
        audit.setTeamExpiryDate(new Date());
        return audit;
    }
