public static List<Audit> createMockAuditList() {
        List<Audit> auditList = new ArrayList<>();

        Audit audit1 = new Audit();
        audit1.setAuditId("12345");
        audit1.setAuditDate("2023-05-22");
        audit1.setAuditType("Type A");
        audit1.setRacfId("racf123");
        audit1.setUserGroup("Group A");
        audit1.setExternalOrderId("Order123");
        audit1.setDate(new Date());
        audit1.setBusinessArea("Area A");
        audit1.setBusinessAreaUserId("user123");
        audit1.setIsCentralPrintSuccess("Yes");
        audit1.setIsLocalPrintSuccess("Yes");
        audit1.setIsArchivalSuccess("Yes");
        audit1.setTemplateId("Template123");
        audit1.setTeamName("Team A");
        audit1.setCentreName("Centre A");
        audit1.setAccountNo("Account123");
        audit1.setTouchPointName("Touchpoint A");
        audit1.setTouchPointGuid("Guid123");
        audit1.setEnvironemntName("Environment A");
        audit1.setSortcode("123456");
        audit1.setBrand("Brand A");
        audit1.setSubBrand("Sub Brand A");
        audit1.setThirdPartyTemplate("Third Party Template");
        audit1.setAddresseeLine1("Address Line 1");
        audit1.setAddresseeLine2("Address Line 2");
        audit1.setAddressLine1("Address Line 1");
        audit1.setAddressLine2("Address Line 2");
        audit1.setAddressLine3("Address Line 3");
        audit1.setAddressLine4("Address Line 4");
        audit1.setAddressLine5("Address Line 5");
        audit1.setPostCode("12345");
        audit1.setPhoneNumberRBS("1234567890");
        audit1.setPhoneNumberNWB("9876543210");
        audit1.setPhoneNumberUBN("0123456789");
        audit1.setLotCodeRbs("Lot Code RBS");
        audit1.setLotCodeNwb("Lot Code NWB");
        audit1.setLotCodeUbn("Lot Code UBN");
        audit1.setOverseasNumberRBS("987654321");
        audit1.setOverseasNumberNWB("123456789");
        audit1.setOverseasNumberUBN("012345678");
        audit1.setBreCode("BRE123");
        audit1.setBreDescription("BRE Description");
        audit1.setSignatory("John Doe");
        audit1.setSignatoryJobTitle("Manager");
        audit1.setSignatorySignature("Signature123");
        audit1.setTeamExpiryDate(new Date());

        Audit audit2 = new Audit();
        audit2.setAuditId("67890");
        audit2.setAuditDate("2023-05-23");
        audit2.setAuditType("Type B");
        audit2.setRacfId("racf456");
        audit2.setUserGroup("Group B");
        audit2.setExternalOrderId("Order456");
        audit2.setDate(new Date());
        audit2.setBusinessArea("Area B");
        audit2.setBusinessAreaUserId("user456");
        audit2.setIsCentralPrintSuccess("No");
        audit2.setIsLocalPrintSuccess("No");
        audit2.setIsArchivalSuccess("No");
        audit2.setTemplateId("Template456");
        audit2.setTeamName("Team B");
        audit2.setCentreName("Centre B");
        audit2.setAccountNo("Account456");
        audit2.setTouchPointName("Touchpoint B");
        audit2.setTouchPointGuid("Guid456");
        audit2.setEnvironemntName("Environment B");
        audit2.setSortcode("654321");
        audit2.setBrand("Brand B");
        audit2.setSubBrand("Sub Brand B");
        audit2.setThirdPartyTemplate("Third Party Template 2");
        audit2.setAddresseeLine1("Address Line 1");
        audit2.setAddresseeLine2("Address Line 2");
        audit2.setAddressLine1("Address Line 1");
        audit2.setAddressLine2("Address Line 2");
        audit2.setAddressLine3("Address Line 3");
        audit2.setAddressLine4("Address Line 4");
        audit2.setAddressLine5("Address Line 5");
        audit2.setPostCode("54321");
        audit2.setPhoneNumberRBS("0987654321");
        audit2.setPhoneNumberNWB("1234567890");
        audit2.setPhoneNumberUBN("9876543210");
        audit2.setLotCodeRbs("Lot Code RBS 2");
        audit2.setLotCodeNwb("Lot Code NWB 2");
        audit2.setLotCodeUbn("Lot Code UBN 2");
        audit2.setOverseasNumberRBS("012345678");
        audit2.setOverseasNumberNWB("987654321");
        audit2.setOverseasNumberUBN("123456789");
        audit2.setBreCode("BRE456");
        audit2.setBreDescription("BRE Description 2");
        audit2.setSignatory("Jane Doe");
        audit2.setSignatoryJobTitle("Supervisor");
        audit2.setSignatorySignature("Signature456");
        audit2.setTeamExpiryDate(new Date());

        auditList.add(audit1);
        auditList.add(audit2);

        return auditList;
    }
