//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientIdentificationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BranchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NodeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Prerelease" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientIdentificationType", propOrder = {
    "branchId",
    "nodeId",
    "prerelease"
})
@XmlSeeAlso({
    RemoveTestRequest.class,
    EditTestRequest.class,
    JobPerformanceReportRequest.class,
    TaskListRequest.class,
    RemoveTaskRequest.class,
    EditTaskRequest.class,
    JobStatusRequest.class,
    ProjectAuditReportRequest.class,
    ProjectListRequest.class,
    ConnectedOrderListRequest.class,
    InitiateConnectedOrderDeliveryRequest.class,
    ApproveConnectedOrderRequest.class,
    ReleaseForApprovalOrActivateConnectedOrderRequest.class,
    RemoveConnectedOrderRequest.class,
    CloneConnectedOrderRequest.class,
    CreateConnectedOrderRequest.class,
    DataSourceListRequest.class,
    TouchpointExportRequest.class,
    TouchpointCloneRequest.class,
    TouchpointImportRequest.class,
    TouchpointCollectionListRequest.class,
    DataResourceListRequest.class,
    TouchpointListRequest.class,
    TouchpointProductionJobListRequest.class,
    TouchpointDeliveryEventRequest.class,
    TestListRequest.class,
    RerunTestRequest.class,
    NodeToNodeCopyRequest.class,
    NodeListRequest.class,
    MessageContentQueryRequest.class,
    DeactivateUserRequest.class,
    JobClientBundleRequest.class,
    JobServerBundleRequest.class,
    JobDiagnosticBundleRequest.class,
    ImportTransactionStatsRequest.class,
    ImportJobStatsRequest.class,
    FileChunkUploadRequest.class,
    FileChunkDownloadRequest.class,
    DomainReportRequest.class,
    UnifiedLoginReportRequest.class,
    CreateActivateUserRequest.class,
    UsersTemplateRequest.class,
    UsersReportRequest.class,
    DeliveryReportRequest.class,
    DeleteFileRequest.class,
    UploadEmailTemplateRequest.class,
    UploadJobReportRequest.class,
    UploadProcessedJobRequest.class,
    CreateDataResourceRequest.class,
    DataFileDownloadRequest.class,
    DataFileUploadRequest.class,
    DataAnonymizeRequest.class,
    CreateSandboxInstanceRequest.class,
    TargetingRulesSearchRequest.class,
    TargetingGroupsSearchRequest.class,
    ContentSearchRequest.class,
    CompositionPackageUploadRequest.class,
    GetBackgroundTaskOutputFileRequest.class,
    GetBackgroundTaskStatusRequest.class,
    SFTPRepoSyncRequest.class,
    CompositionPackageUpdateRequest.class,
    BackgroundImageDownloadRequest.class,
    MessageAuditReportRequest.class,
    MetadataReportRequest.class,
    AuditReportRequest.class,
    ActivateExistingSchemaRequest.class
})
public class ClientIdentificationType {

    @XmlElement(name = "BranchId", required = true)
    protected String branchId;
    @XmlElement(name = "NodeId")
    protected String nodeId;
    @XmlElement(name = "Prerelease")
    protected String prerelease;

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchId(String value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the prerelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrerelease() {
        return prerelease;
    }

    /**
     * Sets the value of the prerelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrerelease(String value) {
        this.prerelease = value;
    }

}
