//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompositionPackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositionPackageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="PackageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CFTemplateFile" type="{http://messagepoint.com/api/schemas}UploadFileType" minOccurs="0"/&gt;
 *         &lt;element name="CompositionFile" type="{http://messagepoint.com/api/schemas}UploadFileType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositionPackageType", propOrder = {

})
public class CompositionPackageType {

    @XmlElement(name = "PackageName")
    protected String packageName;
    @XmlElement(name = "CFTemplateFile")
    protected UploadFileType cfTemplateFile;
    @XmlElement(name = "CompositionFile")
    protected UploadFileType compositionFile;

    /**
     * Gets the value of the packageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * Sets the value of the packageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageName(String value) {
        this.packageName = value;
    }

    /**
     * Gets the value of the cfTemplateFile property.
     * 
     * @return
     *     possible object is
     *     {@link UploadFileType }
     *     
     */
    public UploadFileType getCFTemplateFile() {
        return cfTemplateFile;
    }

    /**
     * Sets the value of the cfTemplateFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadFileType }
     *     
     */
    public void setCFTemplateFile(UploadFileType value) {
        this.cfTemplateFile = value;
    }

    /**
     * Gets the value of the compositionFile property.
     * 
     * @return
     *     possible object is
     *     {@link UploadFileType }
     *     
     */
    public UploadFileType getCompositionFile() {
        return compositionFile;
    }

    /**
     * Sets the value of the compositionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadFileType }
     *     
     */
    public void setCompositionFile(UploadFileType value) {
        this.compositionFile = value;
    }

}
