//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectedOrderStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConnectedOrderStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WORKING_COPY"/&gt;
 *     &lt;enumeration value="PENDING_APPROVAL"/&gt;
 *     &lt;enumeration value="ACTIVE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ConnectedOrderStatusType")
@XmlEnum
public enum ConnectedOrderStatusType {

    WORKING_COPY,
    PENDING_APPROVAL,
    ACTIVE;

    public String value() {
        return name();
    }

    public static ConnectedOrderStatusType fromValue(String v) {
        return valueOf(v);
    }

}
