//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequesterUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AuthorUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AssigneeUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExternalOrderIdList" type="{http://messagepoint.com/api/schemas}ExternalOrderIdListType" minOccurs="0"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://messagepoint.com/api/schemas}ConnectedOrderStatusType" minOccurs="0"/&gt;
 *         &lt;element name="ExplicitResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IncludeTestOrders" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="JobStatusStateToInclude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SlimResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requesterUsername",
    "authorUsername",
    "assigneeUsername",
    "externalOrderIdList",
    "touchpoint",
    "status",
    "explicitResponse",
    "includeTestOrders",
    "jobStatusStateToInclude",
    "slimResponse"
})
@XmlRootElement(name = "ConnectedOrderListRequest")
public class ConnectedOrderListRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "RequesterUsername")
    protected String requesterUsername;
    @XmlElement(name = "AuthorUsername")
    protected String authorUsername;
    @XmlElement(name = "AssigneeUsername")
    protected String assigneeUsername;
    @XmlElement(name = "ExternalOrderIdList")
    protected ExternalOrderIdListType externalOrderIdList;
    @XmlElement(name = "Touchpoint")
    protected TouchpointType touchpoint;
    @XmlElement(name = "Status")
    @XmlSchemaType(name = "string")
    protected ConnectedOrderStatusType status;
    @XmlElement(name = "ExplicitResponse")
    protected Boolean explicitResponse;
    @XmlElement(name = "IncludeTestOrders")
    protected Boolean includeTestOrders;
    @XmlElement(name = "JobStatusStateToInclude")
    protected String jobStatusStateToInclude;
    @XmlElement(name = "SlimResponse")
    protected Boolean slimResponse;

    /**
     * Gets the value of the requesterUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequesterUsername() {
        return requesterUsername;
    }

    /**
     * Sets the value of the requesterUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequesterUsername(String value) {
        this.requesterUsername = value;
    }

    /**
     * Gets the value of the authorUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * Sets the value of the authorUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorUsername(String value) {
        this.authorUsername = value;
    }

    /**
     * Gets the value of the assigneeUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigneeUsername() {
        return assigneeUsername;
    }

    /**
     * Sets the value of the assigneeUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigneeUsername(String value) {
        this.assigneeUsername = value;
    }

    /**
     * Gets the value of the externalOrderIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalOrderIdListType }
     *     
     */
    public ExternalOrderIdListType getExternalOrderIdList() {
        return externalOrderIdList;
    }

    /**
     * Sets the value of the externalOrderIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalOrderIdListType }
     *     
     */
    public void setExternalOrderIdList(ExternalOrderIdListType value) {
        this.externalOrderIdList = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectedOrderStatusType }
     *     
     */
    public ConnectedOrderStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectedOrderStatusType }
     *     
     */
    public void setStatus(ConnectedOrderStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the explicitResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExplicitResponse() {
        return explicitResponse;
    }

    /**
     * Sets the value of the explicitResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExplicitResponse(Boolean value) {
        this.explicitResponse = value;
    }

    /**
     * Gets the value of the includeTestOrders property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeTestOrders() {
        return includeTestOrders;
    }

    /**
     * Sets the value of the includeTestOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeTestOrders(Boolean value) {
        this.includeTestOrders = value;
    }

    /**
     * Gets the value of the jobStatusStateToInclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobStatusStateToInclude() {
        return jobStatusStateToInclude;
    }

    /**
     * Sets the value of the jobStatusStateToInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobStatusStateToInclude(String value) {
        this.jobStatusStateToInclude = value;
    }

    /**
     * Gets the value of the slimResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSlimResponse() {
        return slimResponse;
    }

    /**
     * Sets the value of the slimResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSlimResponse(Boolean value) {
        this.slimResponse = value;
    }

}
