//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectedOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectedOrderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExternalOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AuthorUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AuthorInfo" type="{http://messagepoint.com/api/schemas}UserInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Assigned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrimaryIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastActivationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AwaitingApprovalFrom" type="{http://messagepoint.com/api/schemas}UserInfoListType" minOccurs="0"/&gt;
 *         &lt;element name="ApprovedBy" type="{http://messagepoint.com/api/schemas}UserInfoListType" minOccurs="0"/&gt;
 *         &lt;element name="FinalApprover" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastProductionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tpGuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isTestOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OrderData" type="{http://messagepoint.com/api/schemas}ConnectedOrderDataPointInfoListType" minOccurs="0"/&gt;
 *         &lt;element name="JobStatus" type="{http://messagepoint.com/api/schemas}JobStatusType" minOccurs="0"/&gt;
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectedOrderType", propOrder = {
    "externalOrderId",
    "authorUsername",
    "authorInfo",
    "assigned",
    "primaryIdentifier",
    "status",
    "channel",
    "createdDate",
    "lastActivationDate",
    "awaitingApprovalFrom",
    "approvedBy",
    "finalApprover",
    "lastProductionDate",
    "tpGuid",
    "isTestOrder",
    "orderData",
    "jobStatus",
    "error"
})
public class ConnectedOrderType {

    @XmlElement(name = "ExternalOrderId", required = true)
    protected String externalOrderId;
    @XmlElement(name = "AuthorUsername")
    protected String authorUsername;
    @XmlElement(name = "AuthorInfo")
    protected UserInfoType authorInfo;
    @XmlElement(name = "Assigned")
    protected String assigned;
    @XmlElement(name = "PrimaryIdentifier")
    protected String primaryIdentifier;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Channel")
    protected String channel;
    @XmlElement(name = "CreatedDate")
    protected String createdDate;
    @XmlElement(name = "LastActivationDate")
    protected String lastActivationDate;
    @XmlElement(name = "AwaitingApprovalFrom")
    protected UserInfoListType awaitingApprovalFrom;
    @XmlElement(name = "ApprovedBy")
    protected UserInfoListType approvedBy;
    @XmlElement(name = "FinalApprover")
    protected String finalApprover;
    @XmlElement(name = "LastProductionDate")
    protected String lastProductionDate;
    protected String tpGuid;
    protected Boolean isTestOrder;
    @XmlElement(name = "OrderData")
    protected ConnectedOrderDataPointInfoListType orderData;
    @XmlElement(name = "JobStatus")
    protected JobStatusType jobStatus;
    @XmlElement(name = "Error")
    protected String error;

    /**
     * Gets the value of the externalOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalOrderId() {
        return externalOrderId;
    }

    /**
     * Sets the value of the externalOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalOrderId(String value) {
        this.externalOrderId = value;
    }

    /**
     * Gets the value of the authorUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * Sets the value of the authorUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorUsername(String value) {
        this.authorUsername = value;
    }

    /**
     * Gets the value of the authorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfoType }
     *     
     */
    public UserInfoType getAuthorInfo() {
        return authorInfo;
    }

    /**
     * Sets the value of the authorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfoType }
     *     
     */
    public void setAuthorInfo(UserInfoType value) {
        this.authorInfo = value;
    }

    /**
     * Gets the value of the assigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigned() {
        return assigned;
    }

    /**
     * Sets the value of the assigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigned(String value) {
        this.assigned = value;
    }

    /**
     * Gets the value of the primaryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryIdentifier() {
        return primaryIdentifier;
    }

    /**
     * Sets the value of the primaryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryIdentifier(String value) {
        this.primaryIdentifier = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the lastActivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastActivationDate() {
        return lastActivationDate;
    }

    /**
     * Sets the value of the lastActivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastActivationDate(String value) {
        this.lastActivationDate = value;
    }

    /**
     * Gets the value of the awaitingApprovalFrom property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfoListType }
     *     
     */
    public UserInfoListType getAwaitingApprovalFrom() {
        return awaitingApprovalFrom;
    }

    /**
     * Sets the value of the awaitingApprovalFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfoListType }
     *     
     */
    public void setAwaitingApprovalFrom(UserInfoListType value) {
        this.awaitingApprovalFrom = value;
    }

    /**
     * Gets the value of the approvedBy property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfoListType }
     *     
     */
    public UserInfoListType getApprovedBy() {
        return approvedBy;
    }

    /**
     * Sets the value of the approvedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfoListType }
     *     
     */
    public void setApprovedBy(UserInfoListType value) {
        this.approvedBy = value;
    }

    /**
     * Gets the value of the finalApprover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalApprover() {
        return finalApprover;
    }

    /**
     * Sets the value of the finalApprover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalApprover(String value) {
        this.finalApprover = value;
    }

    /**
     * Gets the value of the lastProductionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastProductionDate() {
        return lastProductionDate;
    }

    /**
     * Sets the value of the lastProductionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastProductionDate(String value) {
        this.lastProductionDate = value;
    }

    /**
     * Gets the value of the tpGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpGuid() {
        return tpGuid;
    }

    /**
     * Sets the value of the tpGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpGuid(String value) {
        this.tpGuid = value;
    }

    /**
     * Gets the value of the isTestOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTestOrder() {
        return isTestOrder;
    }

    /**
     * Sets the value of the isTestOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTestOrder(Boolean value) {
        this.isTestOrder = value;
    }

    /**
     * Gets the value of the orderData property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectedOrderDataPointInfoListType }
     *     
     */
    public ConnectedOrderDataPointInfoListType getOrderData() {
        return orderData;
    }

    /**
     * Sets the value of the orderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectedOrderDataPointInfoListType }
     *     
     */
    public void setOrderData(ConnectedOrderDataPointInfoListType value) {
        this.orderData = value;
    }

    /**
     * Gets the value of the jobStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JobStatusType }
     *     
     */
    public JobStatusType getJobStatus() {
        return jobStatus;
    }

    /**
     * Sets the value of the jobStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobStatusType }
     *     
     */
    public void setJobStatus(JobStatusType value) {
        this.jobStatus = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

}
