//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType"/&gt;
 *         &lt;element name="AuthorUsername" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DataPointList" type="{http://messagepoint.com/api/schemas}ConnectedOrderDataPointListType"/&gt;
 *         &lt;element name="NewExternalOrderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TagCloud" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreateProof" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AutoApprove" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "touchpoint",
    "authorUsername",
    "dataPointList",
    "newExternalOrderId",
    "tagCloud",
    "createProof",
    "email",
    "autoApprove"
})
@XmlRootElement(name = "CreateConnectedOrderRequest")
public class CreateConnectedOrderRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "Touchpoint", required = true)
    protected TouchpointType touchpoint;
    @XmlElement(name = "AuthorUsername", required = true)
    protected String authorUsername;
    @XmlElement(name = "DataPointList", required = true)
    protected ConnectedOrderDataPointListType dataPointList;
    @XmlElement(name = "NewExternalOrderId")
    protected String newExternalOrderId;
    @XmlElement(name = "TagCloud")
    protected String tagCloud;
    @XmlElement(name = "CreateProof")
    protected Boolean createProof;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "AutoApprove")
    protected Boolean autoApprove;

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

    /**
     * Gets the value of the authorUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * Sets the value of the authorUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorUsername(String value) {
        this.authorUsername = value;
    }

    /**
     * Gets the value of the dataPointList property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectedOrderDataPointListType }
     *     
     */
    public ConnectedOrderDataPointListType getDataPointList() {
        return dataPointList;
    }

    /**
     * Sets the value of the dataPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectedOrderDataPointListType }
     *     
     */
    public void setDataPointList(ConnectedOrderDataPointListType value) {
        this.dataPointList = value;
    }

    /**
     * Gets the value of the newExternalOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewExternalOrderId() {
        return newExternalOrderId;
    }

    /**
     * Sets the value of the newExternalOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewExternalOrderId(String value) {
        this.newExternalOrderId = value;
    }

    /**
     * Gets the value of the tagCloud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagCloud() {
        return tagCloud;
    }

    /**
     * Sets the value of the tagCloud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagCloud(String value) {
        this.tagCloud = value;
    }

    /**
     * Gets the value of the createProof property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreateProof() {
        return createProof;
    }

    /**
     * Sets the value of the createProof property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateProof(Boolean value) {
        this.createProof = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the autoApprove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoApprove() {
        return autoApprove;
    }

    /**
     * Sets the value of the autoApprove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoApprove(Boolean value) {
        this.autoApprove = value;
    }

}
