//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PrimaryDataFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReferenceDataFileList" type="{http://messagepoint.com/api/schemas}ReferenceDataFileListType" minOccurs="0"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "primaryDataFileName",
    "referenceDataFileList",
    "touchpoint"
})
@XmlRootElement(name = "CreateDataResourceRequest")
public class CreateDataResourceRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PrimaryDataFileName", required = true)
    protected String primaryDataFileName;
    @XmlElement(name = "ReferenceDataFileList")
    protected ReferenceDataFileListType referenceDataFileList;
    @XmlElement(name = "Touchpoint", required = true)
    protected TouchpointType touchpoint;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the primaryDataFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryDataFileName() {
        return primaryDataFileName;
    }

    /**
     * Sets the value of the primaryDataFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryDataFileName(String value) {
        this.primaryDataFileName = value;
    }

    /**
     * Gets the value of the referenceDataFileList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataFileListType }
     *     
     */
    public ReferenceDataFileListType getReferenceDataFileList() {
        return referenceDataFileList;
    }

    /**
     * Sets the value of the referenceDataFileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataFileListType }
     *     
     */
    public void setReferenceDataFileList(ReferenceDataFileListType value) {
        this.referenceDataFileList = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

}
