//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DataFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SourceType" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ChunkNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="Base64Content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataFileName",
    "sourceType",
    "filename",
    "chunkNumber",
    "base64Content",
    "touchpoint"
})
@XmlRootElement(name = "DataFileUploadRequest")
public class DataFileUploadRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "DataFileName", required = true)
    protected String dataFileName;
    @XmlElement(name = "SourceType")
    protected Integer sourceType;
    @XmlElement(name = "Filename", required = true)
    protected String filename;
    @XmlElement(name = "ChunkNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected long chunkNumber;
    @XmlElement(name = "Base64Content", required = true)
    protected String base64Content;
    @XmlElement(name = "Touchpoint")
    protected List<TouchpointType> touchpoint;

    /**
     * Gets the value of the dataFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFileName() {
        return dataFileName;
    }

    /**
     * Sets the value of the dataFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFileName(String value) {
        this.dataFileName = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSourceType(Integer value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the chunkNumber property.
     * 
     */
    public long getChunkNumber() {
        return chunkNumber;
    }

    /**
     * Sets the value of the chunkNumber property.
     * 
     */
    public void setChunkNumber(long value) {
        this.chunkNumber = value;
    }

    /**
     * Gets the value of the base64Content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64Content() {
        return base64Content;
    }

    /**
     * Sets the value of the base64Content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64Content(String value) {
        this.base64Content = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the touchpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTouchpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TouchpointType }
     * 
     * 
     */
    public List<TouchpointType> getTouchpoint() {
        if (touchpoint == null) {
            touchpoint = new ArrayList<TouchpointType>();
        }
        return this.touchpoint;
    }

}
