//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="outputType" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="includeUserManagementInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="includeLicenseManagementInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="includeFeatureActivationInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outputType",
    "includeUserManagementInfo",
    "includeLicenseManagementInfo",
    "includeFeatureActivationInfo"
})
@XmlRootElement(name = "DomainReportRequest")
public class DomainReportRequest
    extends ClientIdentificationType
{

    @XmlSchemaType(name = "unsignedInt")
    protected long outputType;
    protected Boolean includeUserManagementInfo;
    protected Boolean includeLicenseManagementInfo;
    protected Boolean includeFeatureActivationInfo;

    /**
     * Gets the value of the outputType property.
     * 
     */
    public long getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     */
    public void setOutputType(long value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the includeUserManagementInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeUserManagementInfo() {
        return includeUserManagementInfo;
    }

    /**
     * Sets the value of the includeUserManagementInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeUserManagementInfo(Boolean value) {
        this.includeUserManagementInfo = value;
    }

    /**
     * Gets the value of the includeLicenseManagementInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeLicenseManagementInfo() {
        return includeLicenseManagementInfo;
    }

    /**
     * Sets the value of the includeLicenseManagementInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeLicenseManagementInfo(Boolean value) {
        this.includeLicenseManagementInfo = value;
    }

    /**
     * Gets the value of the includeFeatureActivationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeFeatureActivationInfo() {
        return includeFeatureActivationInfo;
    }

    /**
     * Sets the value of the includeFeatureActivationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeFeatureActivationInfo(Boolean value) {
        this.includeFeatureActivationInfo = value;
    }

}
