//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Guid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType" minOccurs="0"/&gt;
 *         &lt;element name="TestData" type="{http://messagepoint.com/api/schemas}DataResourceType" minOccurs="0"/&gt;
 *         &lt;element name="TestDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="AnalysisMode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="UseAllWorkCopies" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="UseAllWorkCopiesForLibAssets" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "name",
    "touchpoint",
    "testData",
    "testDate",
    "analysisMode",
    "useAllWorkCopies",
    "useAllWorkCopiesForLibAssets"
})
@XmlRootElement(name = "EditTestRequest")
public class EditTestRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "Guid")
    protected String guid;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Touchpoint")
    protected TouchpointType touchpoint;
    @XmlElement(name = "TestData")
    protected DataResourceType testData;
    @XmlElement(name = "TestDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar testDate;
    @XmlElement(name = "AnalysisMode")
    protected Boolean analysisMode;
    @XmlElement(name = "UseAllWorkCopies")
    protected Boolean useAllWorkCopies;
    @XmlElement(name = "UseAllWorkCopiesForLibAssets")
    protected Boolean useAllWorkCopiesForLibAssets;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

    /**
     * Gets the value of the testData property.
     * 
     * @return
     *     possible object is
     *     {@link DataResourceType }
     *     
     */
    public DataResourceType getTestData() {
        return testData;
    }

    /**
     * Sets the value of the testData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataResourceType }
     *     
     */
    public void setTestData(DataResourceType value) {
        this.testData = value;
    }

    /**
     * Gets the value of the testDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestDate() {
        return testDate;
    }

    /**
     * Sets the value of the testDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestDate(XMLGregorianCalendar value) {
        this.testDate = value;
    }

    /**
     * Gets the value of the analysisMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnalysisMode() {
        return analysisMode;
    }

    /**
     * Sets the value of the analysisMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnalysisMode(Boolean value) {
        this.analysisMode = value;
    }

    /**
     * Gets the value of the useAllWorkCopies property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseAllWorkCopies() {
        return useAllWorkCopies;
    }

    /**
     * Sets the value of the useAllWorkCopies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAllWorkCopies(Boolean value) {
        this.useAllWorkCopies = value;
    }

    /**
     * Gets the value of the useAllWorkCopiesForLibAssets property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseAllWorkCopiesForLibAssets() {
        return useAllWorkCopiesForLibAssets;
    }

    /**
     * Sets the value of the useAllWorkCopiesForLibAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAllWorkCopiesForLibAssets(Boolean value) {
        this.useAllWorkCopiesForLibAssets = value;
    }

}
