//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExternalOrderIdList" type="{http://messagepoint.com/api/schemas}ExternalOrderIdListType" minOccurs="0"/&gt;
 *         &lt;element name="Activate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType" minOccurs="0"/&gt;
 *         &lt;element name="TouchpointCollection" type="{http://messagepoint.com/api/schemas}TouchpointCollectionType" minOccurs="0"/&gt;
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IncludedOrders" type="{http://messagepoint.com/api/schemas}IncludeConnectedOrderType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalOrderIdList",
    "activate",
    "touchpoint",
    "touchpointCollection",
    "startDate",
    "endDate",
    "includedOrders"
})
@XmlRootElement(name = "InitiateConnectedOrderDeliveryRequest")
public class InitiateConnectedOrderDeliveryRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "ExternalOrderIdList")
    protected ExternalOrderIdListType externalOrderIdList;
    @XmlElement(name = "Activate")
    protected Boolean activate;
    @XmlElement(name = "Touchpoint")
    protected TouchpointType touchpoint;
    @XmlElement(name = "TouchpointCollection")
    protected TouchpointCollectionType touchpointCollection;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "IncludedOrders")
    @XmlSchemaType(name = "string")
    protected IncludeConnectedOrderType includedOrders;

    /**
     * Gets the value of the externalOrderIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalOrderIdListType }
     *     
     */
    public ExternalOrderIdListType getExternalOrderIdList() {
        return externalOrderIdList;
    }

    /**
     * Sets the value of the externalOrderIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalOrderIdListType }
     *     
     */
    public void setExternalOrderIdList(ExternalOrderIdListType value) {
        this.externalOrderIdList = value;
    }

    /**
     * Gets the value of the activate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActivate() {
        return activate;
    }

    /**
     * Sets the value of the activate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActivate(Boolean value) {
        this.activate = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

    /**
     * Gets the value of the touchpointCollection property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointCollectionType }
     *     
     */
    public TouchpointCollectionType getTouchpointCollection() {
        return touchpointCollection;
    }

    /**
     * Sets the value of the touchpointCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointCollectionType }
     *     
     */
    public void setTouchpointCollection(TouchpointCollectionType value) {
        this.touchpointCollection = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the includedOrders property.
     * 
     * @return
     *     possible object is
     *     {@link IncludeConnectedOrderType }
     *     
     */
    public IncludeConnectedOrderType getIncludedOrders() {
        return includedOrders;
    }

    /**
     * Sets the value of the includedOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludeConnectedOrderType }
     *     
     */
    public void setIncludedOrders(IncludeConnectedOrderType value) {
        this.includedOrders = value;
    }

}
