//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccp.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActivateExistingSchemaResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ActivateExistingSchemaResponse");
    private final static QName _AuditReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "AuditReportResponse");
    private final static QName _MetadataReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "MetadataReportResponse");
    private final static QName _MessageAuditReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "MessageAuditReportResponse");
    private final static QName _CompositionPackageUpdateResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CompositionPackageUpdateResponse");
    private final static QName _SFTPRepoSyncResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "SFTPRepoSyncResponse");
    private final static QName _GetBackgroundTaskStatusResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "GetBackgroundTaskStatusResponse");
    private final static QName _GetBackgroundTaskOutputFileResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "GetBackgroundTaskOutputFileResponse");
    private final static QName _CompositionPackageUploadResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CompositionPackageUploadResponse");
    private final static QName _CompositionPackageListRequest_QNAME = new QName("http://messagepoint.com/api/schemas", "CompositionPackageListRequest");
    private final static QName _CompositionPackageListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CompositionPackageListResponse");
    private final static QName _ContentSearchResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ContentSearchResponse");
    private final static QName _TargetingGroupsSearchResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TargetingGroupsSearchResponse");
    private final static QName _TargetingRulesSearchResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TargetingRulesSearchResponse");
    private final static QName _CreateSandboxInstanceResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CreateSandboxInstanceResponse");
    private final static QName _DataAnonymizeResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataAnonymizeResponse");
    private final static QName _DataFileListRequest_QNAME = new QName("http://messagepoint.com/api/schemas", "DataFileListRequest");
    private final static QName _DataFileListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataFileListResponse");
    private final static QName _DataFileUploadResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataFileUploadResponse");
    private final static QName _DataFileDownloadResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataFileDownloadResponse");
    private final static QName _CreateDataResourceResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CreateDataResourceResponse");
    private final static QName _UploadProcessedJobResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UploadProcessedJobResponse");
    private final static QName _UploadJobReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UploadJobReportResponse");
    private final static QName _UploadEmailTemplateResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UploadEmailTemplateResponse");
    private final static QName _DeleteFileResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DeleteFileResponse");
    private final static QName _DeliveryReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DeliveryReportResponse");
    private final static QName _DiagnosticRequest_QNAME = new QName("http://messagepoint.com/api/schemas", "DiagnosticRequest");
    private final static QName _DiagnosticResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DiagnosticResponse");
    private final static QName _UsersReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UsersReportResponse");
    private final static QName _UsersTemplateResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UsersTemplateResponse");
    private final static QName _CreateActivateUserResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CreateActivateUserResponse");
    private final static QName _UnifiedLoginReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "UnifiedLoginReportResponse");
    private final static QName _DomainReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DomainReportResponse");
    private final static QName _FileChunkDownloadResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "FileChunkDownloadResponse");
    private final static QName _FileChunkUploadResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "FileChunkUploadResponse");
    private final static QName _FileListRequest_QNAME = new QName("http://messagepoint.com/api/schemas", "FileListRequest");
    private final static QName _FileListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "FileListResponse");
    private final static QName _ImportJobStatsResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ImportJobStatsResponse");
    private final static QName _ImportTransactionStatsResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ImportTransactionStatsResponse");
    private final static QName _JobDiagnosticBundleResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "JobDiagnosticBundleResponse");
    private final static QName _JobServerBundleResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "JobServerBundleResponse");
    private final static QName _JobClientBundleResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "JobClientBundleResponse");
    private final static QName _DeactivateUserResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DeactivateUserResponse");
    private final static QName _MessageListRequest_QNAME = new QName("http://messagepoint.com/api/schemas", "MessageListRequest");
    private final static QName _MessageListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "MessageListResponse");
    private final static QName _MessageContentQueryResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "MessageContentQueryResponse");
    private final static QName _NodeListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "NodeListResponse");
    private final static QName _NodeToNodeCopyResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "NodeToNodeCopyResponse");
    private final static QName _RerunTestResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "RerunTestResponse");
    private final static QName _TestListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TestListResponse");
    private final static QName _TouchpointDeliveryEventResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointDeliveryEventResponse");
    private final static QName _TouchpointProductionJobListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointProductionJobListResponse");
    private final static QName _TouchpointListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointListResponse");
    private final static QName _DataResourceListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataResourceListResponse");
    private final static QName _TouchpointCollectionListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointCollectionListResponse");
    private final static QName _TouchpointImportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointImportResponse");
    private final static QName _TouchpointCloneResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointCloneResponse");
    private final static QName _TouchpointExportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TouchpointExportResponse");
    private final static QName _DataSourceListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "DataSourceListResponse");
    private final static QName _CreateConnectedOrderResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CreateConnectedOrderResponse");
    private final static QName _CloneConnectedOrderResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "CloneConnectedOrderResponse");
    private final static QName _RemoveConnectedOrderResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "RemoveConnectedOrderResponse");
    private final static QName _ReleaseForApprovalOrActivateConnectedOrderResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ReleaseForApprovalOrActivateConnectedOrderResponse");
    private final static QName _ApproveConnectedOrderResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ApproveConnectedOrderResponse");
    private final static QName _InitiateConnectedOrderDeliveryResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "InitiateConnectedOrderDeliveryResponse");
    private final static QName _ConnectedOrderListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ConnectedOrderListResponse");
    private final static QName _ProjectListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ProjectListResponse");
    private final static QName _ProjectAuditReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "ProjectAuditReportResponse");
    private final static QName _JobStatusResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "JobStatusResponse");
    private final static QName _EditTaskResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "EditTaskResponse");
    private final static QName _RemoveTaskResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "RemoveTaskResponse");
    private final static QName _TaskListResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "TaskListResponse");
    private final static QName _JobPerformanceReportResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "JobPerformanceReportResponse");
    private final static QName _EditTestResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "EditTestResponse");
    private final static QName _RemoveTestResponse_QNAME = new QName("http://messagepoint.com/api/schemas", "RemoveTestResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccp.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivateExistingSchemaRequest }
     * 
     */
    public ActivateExistingSchemaRequest createActivateExistingSchemaRequest() {
        return new ActivateExistingSchemaRequest();
    }

    /**
     * Create an instance of {@link ClientIdentificationType }
     * 
     */
    public ClientIdentificationType createClientIdentificationType() {
        return new ClientIdentificationType();
    }

    /**
     * Create an instance of {@link SimpleResponseType }
     * 
     */
    public SimpleResponseType createSimpleResponseType() {
        return new SimpleResponseType();
    }

    /**
     * Create an instance of {@link AuditReportRequest }
     * 
     */
    public AuditReportRequest createAuditReportRequest() {
        return new AuditReportRequest();
    }

    /**
     * Create an instance of {@link TouchpointType }
     * 
     */
    public TouchpointType createTouchpointType() {
        return new TouchpointType();
    }

    /**
     * Create an instance of {@link FileResponseType }
     * 
     */
    public FileResponseType createFileResponseType() {
        return new FileResponseType();
    }

    /**
     * Create an instance of {@link MetadataReportRequest }
     * 
     */
    public MetadataReportRequest createMetadataReportRequest() {
        return new MetadataReportRequest();
    }

    /**
     * Create an instance of {@link MessageAuditReportRequest }
     * 
     */
    public MessageAuditReportRequest createMessageAuditReportRequest() {
        return new MessageAuditReportRequest();
    }

    /**
     * Create an instance of {@link BackgroundImageDownloadRequest }
     * 
     */
    public BackgroundImageDownloadRequest createBackgroundImageDownloadRequest() {
        return new BackgroundImageDownloadRequest();
    }

    /**
     * Create an instance of {@link BackgroundImageDownloadResponse }
     * 
     */
    public BackgroundImageDownloadResponse createBackgroundImageDownloadResponse() {
        return new BackgroundImageDownloadResponse();
    }

    /**
     * Create an instance of {@link SectionFileType }
     * 
     */
    public SectionFileType createSectionFileType() {
        return new SectionFileType();
    }

    /**
     * Create an instance of {@link CompositionPackageUpdateRequest }
     * 
     */
    public CompositionPackageUpdateRequest createCompositionPackageUpdateRequest() {
        return new CompositionPackageUpdateRequest();
    }

    /**
     * Create an instance of {@link CompositionPackageType }
     * 
     */
    public CompositionPackageType createCompositionPackageType() {
        return new CompositionPackageType();
    }

    /**
     * Create an instance of {@link SFTPRepoSyncRequest }
     * 
     */
    public SFTPRepoSyncRequest createSFTPRepoSyncRequest() {
        return new SFTPRepoSyncRequest();
    }

    /**
     * Create an instance of {@link BackgroundTaskIdentificationResponseType }
     * 
     */
    public BackgroundTaskIdentificationResponseType createBackgroundTaskIdentificationResponseType() {
        return new BackgroundTaskIdentificationResponseType();
    }

    /**
     * Create an instance of {@link GetBackgroundTaskStatusRequest }
     * 
     */
    public GetBackgroundTaskStatusRequest createGetBackgroundTaskStatusRequest() {
        return new GetBackgroundTaskStatusRequest();
    }

    /**
     * Create an instance of {@link BackgroundTaskStatusType }
     * 
     */
    public BackgroundTaskStatusType createBackgroundTaskStatusType() {
        return new BackgroundTaskStatusType();
    }

    /**
     * Create an instance of {@link GetBackgroundTaskOutputFileRequest }
     * 
     */
    public GetBackgroundTaskOutputFileRequest createGetBackgroundTaskOutputFileRequest() {
        return new GetBackgroundTaskOutputFileRequest();
    }

    /**
     * Create an instance of {@link CompositionPackageUploadRequest }
     * 
     */
    public CompositionPackageUploadRequest createCompositionPackageUploadRequest() {
        return new CompositionPackageUploadRequest();
    }

    /**
     * Create an instance of {@link TouchpointCollectionType }
     * 
     */
    public TouchpointCollectionType createTouchpointCollectionType() {
        return new TouchpointCollectionType();
    }

    /**
     * Create an instance of {@link ObjectCreateResponseType }
     * 
     */
    public ObjectCreateResponseType createObjectCreateResponseType() {
        return new ObjectCreateResponseType();
    }

    /**
     * Create an instance of {@link ObjectListResponseType }
     * 
     */
    public ObjectListResponseType createObjectListResponseType() {
        return new ObjectListResponseType();
    }

    /**
     * Create an instance of {@link ContentSearchRequest }
     * 
     */
    public ContentSearchRequest createContentSearchRequest() {
        return new ContentSearchRequest();
    }

    /**
     * Create an instance of {@link TargetingGroupsSearchRequest }
     * 
     */
    public TargetingGroupsSearchRequest createTargetingGroupsSearchRequest() {
        return new TargetingGroupsSearchRequest();
    }

    /**
     * Create an instance of {@link TargetingRulesSearchRequest }
     * 
     */
    public TargetingRulesSearchRequest createTargetingRulesSearchRequest() {
        return new TargetingRulesSearchRequest();
    }

    /**
     * Create an instance of {@link CreateSandboxInstanceRequest }
     * 
     */
    public CreateSandboxInstanceRequest createCreateSandboxInstanceRequest() {
        return new CreateSandboxInstanceRequest();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link DataAnonymizeRequest }
     * 
     */
    public DataAnonymizeRequest createDataAnonymizeRequest() {
        return new DataAnonymizeRequest();
    }

    /**
     * Create an instance of {@link DataFileUploadRequest }
     * 
     */
    public DataFileUploadRequest createDataFileUploadRequest() {
        return new DataFileUploadRequest();
    }

    /**
     * Create an instance of {@link DataFileDownloadRequest }
     * 
     */
    public DataFileDownloadRequest createDataFileDownloadRequest() {
        return new DataFileDownloadRequest();
    }

    /**
     * Create an instance of {@link CreateDataResourceRequest }
     * 
     */
    public CreateDataResourceRequest createCreateDataResourceRequest() {
        return new CreateDataResourceRequest();
    }

    /**
     * Create an instance of {@link ReferenceDataFileListType }
     * 
     */
    public ReferenceDataFileListType createReferenceDataFileListType() {
        return new ReferenceDataFileListType();
    }

    /**
     * Create an instance of {@link UploadProcessedJobRequest }
     * 
     */
    public UploadProcessedJobRequest createUploadProcessedJobRequest() {
        return new UploadProcessedJobRequest();
    }

    /**
     * Create an instance of {@link UploadJobReportRequest }
     * 
     */
    public UploadJobReportRequest createUploadJobReportRequest() {
        return new UploadJobReportRequest();
    }

    /**
     * Create an instance of {@link UploadEmailTemplateRequest }
     * 
     */
    public UploadEmailTemplateRequest createUploadEmailTemplateRequest() {
        return new UploadEmailTemplateRequest();
    }

    /**
     * Create an instance of {@link DeleteFileRequest }
     * 
     */
    public DeleteFileRequest createDeleteFileRequest() {
        return new DeleteFileRequest();
    }

    /**
     * Create an instance of {@link FileListType }
     * 
     */
    public FileListType createFileListType() {
        return new FileListType();
    }

    /**
     * Create an instance of {@link DeliveryReportRequest }
     * 
     */
    public DeliveryReportRequest createDeliveryReportRequest() {
        return new DeliveryReportRequest();
    }

    /**
     * Create an instance of {@link MessageListType }
     * 
     */
    public MessageListType createMessageListType() {
        return new MessageListType();
    }

    /**
     * Create an instance of {@link UsersReportRequest }
     * 
     */
    public UsersReportRequest createUsersReportRequest() {
        return new UsersReportRequest();
    }

    /**
     * Create an instance of {@link UsersTemplateRequest }
     * 
     */
    public UsersTemplateRequest createUsersTemplateRequest() {
        return new UsersTemplateRequest();
    }

    /**
     * Create an instance of {@link CreateActivateUserRequest }
     * 
     */
    public CreateActivateUserRequest createCreateActivateUserRequest() {
        return new CreateActivateUserRequest();
    }

    /**
     * Create an instance of {@link UnifiedLoginReportRequest }
     * 
     */
    public UnifiedLoginReportRequest createUnifiedLoginReportRequest() {
        return new UnifiedLoginReportRequest();
    }

    /**
     * Create an instance of {@link DomainReportRequest }
     * 
     */
    public DomainReportRequest createDomainReportRequest() {
        return new DomainReportRequest();
    }

    /**
     * Create an instance of {@link FileChunkDownloadRequest }
     * 
     */
    public FileChunkDownloadRequest createFileChunkDownloadRequest() {
        return new FileChunkDownloadRequest();
    }

    /**
     * Create an instance of {@link FileChunkUploadRequest }
     * 
     */
    public FileChunkUploadRequest createFileChunkUploadRequest() {
        return new FileChunkUploadRequest();
    }

    /**
     * Create an instance of {@link ImportJobStatsRequest }
     * 
     */
    public ImportJobStatsRequest createImportJobStatsRequest() {
        return new ImportJobStatsRequest();
    }

    /**
     * Create an instance of {@link ImportTransactionStatsRequest }
     * 
     */
    public ImportTransactionStatsRequest createImportTransactionStatsRequest() {
        return new ImportTransactionStatsRequest();
    }

    /**
     * Create an instance of {@link JobDiagnosticBundleRequest }
     * 
     */
    public JobDiagnosticBundleRequest createJobDiagnosticBundleRequest() {
        return new JobDiagnosticBundleRequest();
    }

    /**
     * Create an instance of {@link JobServerBundleRequest }
     * 
     */
    public JobServerBundleRequest createJobServerBundleRequest() {
        return new JobServerBundleRequest();
    }

    /**
     * Create an instance of {@link JobClientBundleRequest }
     * 
     */
    public JobClientBundleRequest createJobClientBundleRequest() {
        return new JobClientBundleRequest();
    }

    /**
     * Create an instance of {@link DeactivateUserRequest }
     * 
     */
    public DeactivateUserRequest createDeactivateUserRequest() {
        return new DeactivateUserRequest();
    }

    /**
     * Create an instance of {@link MessageContentQueryRequest }
     * 
     */
    public MessageContentQueryRequest createMessageContentQueryRequest() {
        return new MessageContentQueryRequest();
    }

    /**
     * Create an instance of {@link NodeListRequest }
     * 
     */
    public NodeListRequest createNodeListRequest() {
        return new NodeListRequest();
    }

    /**
     * Create an instance of {@link NodeToNodeCopyRequest }
     * 
     */
    public NodeToNodeCopyRequest createNodeToNodeCopyRequest() {
        return new NodeToNodeCopyRequest();
    }

    /**
     * Create an instance of {@link RerunTestRequest }
     * 
     */
    public RerunTestRequest createRerunTestRequest() {
        return new RerunTestRequest();
    }

    /**
     * Create an instance of {@link TestListRequest }
     * 
     */
    public TestListRequest createTestListRequest() {
        return new TestListRequest();
    }

    /**
     * Create an instance of {@link TouchpointDeliveryEventRequest }
     * 
     */
    public TouchpointDeliveryEventRequest createTouchpointDeliveryEventRequest() {
        return new TouchpointDeliveryEventRequest();
    }

    /**
     * Create an instance of {@link TouchpointProductionJobListRequest }
     * 
     */
    public TouchpointProductionJobListRequest createTouchpointProductionJobListRequest() {
        return new TouchpointProductionJobListRequest();
    }

    /**
     * Create an instance of {@link TouchpointListRequest }
     * 
     */
    public TouchpointListRequest createTouchpointListRequest() {
        return new TouchpointListRequest();
    }

    /**
     * Create an instance of {@link DataResourceListRequest }
     * 
     */
    public DataResourceListRequest createDataResourceListRequest() {
        return new DataResourceListRequest();
    }

    /**
     * Create an instance of {@link TouchpointCollectionListRequest }
     * 
     */
    public TouchpointCollectionListRequest createTouchpointCollectionListRequest() {
        return new TouchpointCollectionListRequest();
    }

    /**
     * Create an instance of {@link TouchpointImportRequest }
     * 
     */
    public TouchpointImportRequest createTouchpointImportRequest() {
        return new TouchpointImportRequest();
    }

    /**
     * Create an instance of {@link TouchpointCloneRequest }
     * 
     */
    public TouchpointCloneRequest createTouchpointCloneRequest() {
        return new TouchpointCloneRequest();
    }

    /**
     * Create an instance of {@link TouchpointExportRequest }
     * 
     */
    public TouchpointExportRequest createTouchpointExportRequest() {
        return new TouchpointExportRequest();
    }

    /**
     * Create an instance of {@link DataSourceListRequest }
     * 
     */
    public DataSourceListRequest createDataSourceListRequest() {
        return new DataSourceListRequest();
    }

    /**
     * Create an instance of {@link CreateConnectedOrderRequest }
     * 
     */
    public CreateConnectedOrderRequest createCreateConnectedOrderRequest() {
        return new CreateConnectedOrderRequest();
    }

    /**
     * Create an instance of {@link ConnectedOrderDataPointListType }
     * 
     */
    public ConnectedOrderDataPointListType createConnectedOrderDataPointListType() {
        return new ConnectedOrderDataPointListType();
    }

    /**
     * Create an instance of {@link CreateConnectedOrderResponseType }
     * 
     */
    public CreateConnectedOrderResponseType createCreateConnectedOrderResponseType() {
        return new CreateConnectedOrderResponseType();
    }

    /**
     * Create an instance of {@link CloneConnectedOrderRequest }
     * 
     */
    public CloneConnectedOrderRequest createCloneConnectedOrderRequest() {
        return new CloneConnectedOrderRequest();
    }

    /**
     * Create an instance of {@link CloneConnectedOrderResponseType }
     * 
     */
    public CloneConnectedOrderResponseType createCloneConnectedOrderResponseType() {
        return new CloneConnectedOrderResponseType();
    }

    /**
     * Create an instance of {@link RemoveConnectedOrderRequest }
     * 
     */
    public RemoveConnectedOrderRequest createRemoveConnectedOrderRequest() {
        return new RemoveConnectedOrderRequest();
    }

    /**
     * Create an instance of {@link ExternalOrderIdListType }
     * 
     */
    public ExternalOrderIdListType createExternalOrderIdListType() {
        return new ExternalOrderIdListType();
    }

    /**
     * Create an instance of {@link ReleaseForApprovalOrActivateConnectedOrderRequest }
     * 
     */
    public ReleaseForApprovalOrActivateConnectedOrderRequest createReleaseForApprovalOrActivateConnectedOrderRequest() {
        return new ReleaseForApprovalOrActivateConnectedOrderRequest();
    }

    /**
     * Create an instance of {@link ApproveConnectedOrderRequest }
     * 
     */
    public ApproveConnectedOrderRequest createApproveConnectedOrderRequest() {
        return new ApproveConnectedOrderRequest();
    }

    /**
     * Create an instance of {@link InitiateConnectedOrderDeliveryRequest }
     * 
     */
    public InitiateConnectedOrderDeliveryRequest createInitiateConnectedOrderDeliveryRequest() {
        return new InitiateConnectedOrderDeliveryRequest();
    }

    /**
     * Create an instance of {@link ConnectedOrderListRequest }
     * 
     */
    public ConnectedOrderListRequest createConnectedOrderListRequest() {
        return new ConnectedOrderListRequest();
    }

    /**
     * Create an instance of {@link ProjectListRequest }
     * 
     */
    public ProjectListRequest createProjectListRequest() {
        return new ProjectListRequest();
    }

    /**
     * Create an instance of {@link GuidListType }
     * 
     */
    public GuidListType createGuidListType() {
        return new GuidListType();
    }

    /**
     * Create an instance of {@link ProjectAuditReportRequest }
     * 
     */
    public ProjectAuditReportRequest createProjectAuditReportRequest() {
        return new ProjectAuditReportRequest();
    }

    /**
     * Create an instance of {@link JobStatusRequest }
     * 
     */
    public JobStatusRequest createJobStatusRequest() {
        return new JobStatusRequest();
    }

    /**
     * Create an instance of {@link JobStatusResponseType }
     * 
     */
    public JobStatusResponseType createJobStatusResponseType() {
        return new JobStatusResponseType();
    }

    /**
     * Create an instance of {@link EditTaskRequest }
     * 
     */
    public EditTaskRequest createEditTaskRequest() {
        return new EditTaskRequest();
    }

    /**
     * Create an instance of {@link RemoveTaskRequest }
     * 
     */
    public RemoveTaskRequest createRemoveTaskRequest() {
        return new RemoveTaskRequest();
    }

    /**
     * Create an instance of {@link TaskListRequest }
     * 
     */
    public TaskListRequest createTaskListRequest() {
        return new TaskListRequest();
    }

    /**
     * Create an instance of {@link JobPerformanceReportRequest }
     * 
     */
    public JobPerformanceReportRequest createJobPerformanceReportRequest() {
        return new JobPerformanceReportRequest();
    }

    /**
     * Create an instance of {@link EditTestRequest }
     * 
     */
    public EditTestRequest createEditTestRequest() {
        return new EditTestRequest();
    }

    /**
     * Create an instance of {@link DataResourceType }
     * 
     */
    public DataResourceType createDataResourceType() {
        return new DataResourceType();
    }

    /**
     * Create an instance of {@link RemoveTestRequest }
     * 
     */
    public RemoveTestRequest createRemoveTestRequest() {
        return new RemoveTestRequest();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link UploadFileType }
     * 
     */
    public UploadFileType createUploadFileType() {
        return new UploadFileType();
    }

    /**
     * Create an instance of {@link ObjectListType }
     * 
     */
    public ObjectListType createObjectListType() {
        return new ObjectListType();
    }

    /**
     * Create an instance of {@link JobListType }
     * 
     */
    public JobListType createJobListType() {
        return new JobListType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link NodeListType }
     * 
     */
    public NodeListType createNodeListType() {
        return new NodeListType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link TargetGroupsSearchResponseType }
     * 
     */
    public TargetGroupsSearchResponseType createTargetGroupsSearchResponseType() {
        return new TargetGroupsSearchResponseType();
    }

    /**
     * Create an instance of {@link TargetRulesSearchResponseType }
     * 
     */
    public TargetRulesSearchResponseType createTargetRulesSearchResponseType() {
        return new TargetRulesSearchResponseType();
    }

    /**
     * Create an instance of {@link BackgroundTaskStatusDetailsType }
     * 
     */
    public BackgroundTaskStatusDetailsType createBackgroundTaskStatusDetailsType() {
        return new BackgroundTaskStatusDetailsType();
    }

    /**
     * Create an instance of {@link ConnectedOrderDataPointType }
     * 
     */
    public ConnectedOrderDataPointType createConnectedOrderDataPointType() {
        return new ConnectedOrderDataPointType();
    }

    /**
     * Create an instance of {@link TouchpointListType }
     * 
     */
    public TouchpointListType createTouchpointListType() {
        return new TouchpointListType();
    }

    /**
     * Create an instance of {@link TouchpointInfoType }
     * 
     */
    public TouchpointInfoType createTouchpointInfoType() {
        return new TouchpointInfoType();
    }

    /**
     * Create an instance of {@link ChannelsListType }
     * 
     */
    public ChannelsListType createChannelsListType() {
        return new ChannelsListType();
    }

    /**
     * Create an instance of {@link ChannelsInfoType }
     * 
     */
    public ChannelsInfoType createChannelsInfoType() {
        return new ChannelsInfoType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link ConnectedOrderListType }
     * 
     */
    public ConnectedOrderListType createConnectedOrderListType() {
        return new ConnectedOrderListType();
    }

    /**
     * Create an instance of {@link ConnectedOrderType }
     * 
     */
    public ConnectedOrderType createConnectedOrderType() {
        return new ConnectedOrderType();
    }

    /**
     * Create an instance of {@link UserInfoListType }
     * 
     */
    public UserInfoListType createUserInfoListType() {
        return new UserInfoListType();
    }

    /**
     * Create an instance of {@link UserInfoType }
     * 
     */
    public UserInfoType createUserInfoType() {
        return new UserInfoType();
    }

    /**
     * Create an instance of {@link ConnectedOrderDataPointInfoListType }
     * 
     */
    public ConnectedOrderDataPointInfoListType createConnectedOrderDataPointInfoListType() {
        return new ConnectedOrderDataPointInfoListType();
    }

    /**
     * Create an instance of {@link ConnectedOrderDataPointInfoType }
     * 
     */
    public ConnectedOrderDataPointInfoType createConnectedOrderDataPointInfoType() {
        return new ConnectedOrderDataPointInfoType();
    }

    /**
     * Create an instance of {@link JobStatusType }
     * 
     */
    public JobStatusType createJobStatusType() {
        return new JobStatusType();
    }

    /**
     * Create an instance of {@link ReferenceDataFileType }
     * 
     */
    public ReferenceDataFileType createReferenceDataFileType() {
        return new ReferenceDataFileType();
    }

    /**
     * Create an instance of {@link DataSourceListType }
     * 
     */
    public DataSourceListType createDataSourceListType() {
        return new DataSourceListType();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link DataElementListType }
     * 
     */
    public DataElementListType createDataElementListType() {
        return new DataElementListType();
    }

    /**
     * Create an instance of {@link DataElementType }
     * 
     */
    public DataElementType createDataElementType() {
        return new DataElementType();
    }

    /**
     * Create an instance of {@link TaskListType }
     * 
     */
    public TaskListType createTaskListType() {
        return new TaskListType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ActivateExistingSchemaResponse")
    public JAXBElement<SimpleResponseType> createActivateExistingSchemaResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_ActivateExistingSchemaResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "AuditReportResponse")
    public JAXBElement<FileResponseType> createAuditReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_AuditReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "MetadataReportResponse")
    public JAXBElement<FileResponseType> createMetadataReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_MetadataReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "MessageAuditReportResponse")
    public JAXBElement<FileResponseType> createMessageAuditReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_MessageAuditReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CompositionPackageUpdateResponse")
    public JAXBElement<SimpleResponseType> createCompositionPackageUpdateResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_CompositionPackageUpdateResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "SFTPRepoSyncResponse")
    public JAXBElement<BackgroundTaskIdentificationResponseType> createSFTPRepoSyncResponse(BackgroundTaskIdentificationResponseType value) {
        return new JAXBElement<BackgroundTaskIdentificationResponseType>(_SFTPRepoSyncResponse_QNAME, BackgroundTaskIdentificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskStatusType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskStatusType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "GetBackgroundTaskStatusResponse")
    public JAXBElement<BackgroundTaskStatusType> createGetBackgroundTaskStatusResponse(BackgroundTaskStatusType value) {
        return new JAXBElement<BackgroundTaskStatusType>(_GetBackgroundTaskStatusResponse_QNAME, BackgroundTaskStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "GetBackgroundTaskOutputFileResponse")
    public JAXBElement<FileResponseType> createGetBackgroundTaskOutputFileResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_GetBackgroundTaskOutputFileResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CompositionPackageUploadResponse")
    public JAXBElement<ObjectCreateResponseType> createCompositionPackageUploadResponse(ObjectCreateResponseType value) {
        return new JAXBElement<ObjectCreateResponseType>(_CompositionPackageUploadResponse_QNAME, ObjectCreateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CompositionPackageListRequest")
    public JAXBElement<ClientIdentificationType> createCompositionPackageListRequest(ClientIdentificationType value) {
        return new JAXBElement<ClientIdentificationType>(_CompositionPackageListRequest_QNAME, ClientIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CompositionPackageListResponse")
    public JAXBElement<ObjectListResponseType> createCompositionPackageListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_CompositionPackageListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ContentSearchResponse")
    public JAXBElement<ObjectListResponseType> createContentSearchResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_ContentSearchResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TargetingGroupsSearchResponse")
    public JAXBElement<ObjectListResponseType> createTargetingGroupsSearchResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TargetingGroupsSearchResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TargetingRulesSearchResponse")
    public JAXBElement<ObjectListResponseType> createTargetingRulesSearchResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TargetingRulesSearchResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CreateSandboxInstanceResponse")
    public JAXBElement<SimpleResponseType> createCreateSandboxInstanceResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_CreateSandboxInstanceResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataAnonymizeResponse")
    public JAXBElement<FileResponseType> createDataAnonymizeResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_DataAnonymizeResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataFileListRequest")
    public JAXBElement<ClientIdentificationType> createDataFileListRequest(ClientIdentificationType value) {
        return new JAXBElement<ClientIdentificationType>(_DataFileListRequest_QNAME, ClientIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataFileListResponse")
    public JAXBElement<ObjectListResponseType> createDataFileListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_DataFileListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataFileUploadResponse")
    public JAXBElement<SimpleResponseType> createDataFileUploadResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_DataFileUploadResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataFileDownloadResponse")
    public JAXBElement<FileResponseType> createDataFileDownloadResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_DataFileDownloadResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CreateDataResourceResponse")
    public JAXBElement<SimpleResponseType> createCreateDataResourceResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_CreateDataResourceResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UploadProcessedJobResponse")
    public JAXBElement<SimpleResponseType> createUploadProcessedJobResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_UploadProcessedJobResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UploadJobReportResponse")
    public JAXBElement<SimpleResponseType> createUploadJobReportResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_UploadJobReportResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UploadEmailTemplateResponse")
    public JAXBElement<SimpleResponseType> createUploadEmailTemplateResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_UploadEmailTemplateResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DeleteFileResponse")
    public JAXBElement<SimpleResponseType> createDeleteFileResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_DeleteFileResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DeliveryReportResponse")
    public JAXBElement<ObjectListResponseType> createDeliveryReportResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_DeliveryReportResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DiagnosticRequest")
    public JAXBElement<ClientIdentificationType> createDiagnosticRequest(ClientIdentificationType value) {
        return new JAXBElement<ClientIdentificationType>(_DiagnosticRequest_QNAME, ClientIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DiagnosticResponse")
    public JAXBElement<FileResponseType> createDiagnosticResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_DiagnosticResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UsersReportResponse")
    public JAXBElement<FileResponseType> createUsersReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_UsersReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UsersTemplateResponse")
    public JAXBElement<FileResponseType> createUsersTemplateResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_UsersTemplateResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CreateActivateUserResponse")
    public JAXBElement<SimpleResponseType> createCreateActivateUserResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_CreateActivateUserResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "UnifiedLoginReportResponse")
    public JAXBElement<FileResponseType> createUnifiedLoginReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_UnifiedLoginReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DomainReportResponse")
    public JAXBElement<FileResponseType> createDomainReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_DomainReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "FileChunkDownloadResponse")
    public JAXBElement<FileResponseType> createFileChunkDownloadResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_FileChunkDownloadResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "FileChunkUploadResponse")
    public JAXBElement<SimpleResponseType> createFileChunkUploadResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_FileChunkUploadResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "FileListRequest")
    public JAXBElement<ClientIdentificationType> createFileListRequest(ClientIdentificationType value) {
        return new JAXBElement<ClientIdentificationType>(_FileListRequest_QNAME, ClientIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileListType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileListType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "FileListResponse")
    public JAXBElement<FileListType> createFileListResponse(FileListType value) {
        return new JAXBElement<FileListType>(_FileListResponse_QNAME, FileListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ImportJobStatsResponse")
    public JAXBElement<SimpleResponseType> createImportJobStatsResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_ImportJobStatsResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ImportTransactionStatsResponse")
    public JAXBElement<SimpleResponseType> createImportTransactionStatsResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_ImportTransactionStatsResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "JobDiagnosticBundleResponse")
    public JAXBElement<FileResponseType> createJobDiagnosticBundleResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_JobDiagnosticBundleResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "JobServerBundleResponse")
    public JAXBElement<FileResponseType> createJobServerBundleResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_JobServerBundleResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "JobClientBundleResponse")
    public JAXBElement<FileResponseType> createJobClientBundleResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_JobClientBundleResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DeactivateUserResponse")
    public JAXBElement<SimpleResponseType> createDeactivateUserResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_DeactivateUserResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClientIdentificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "MessageListRequest")
    public JAXBElement<ClientIdentificationType> createMessageListRequest(ClientIdentificationType value) {
        return new JAXBElement<ClientIdentificationType>(_MessageListRequest_QNAME, ClientIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "MessageListResponse")
    public JAXBElement<ObjectListResponseType> createMessageListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_MessageListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "MessageContentQueryResponse")
    public JAXBElement<ObjectListResponseType> createMessageContentQueryResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_MessageContentQueryResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "NodeListResponse")
    public JAXBElement<ObjectListResponseType> createNodeListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_NodeListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "NodeToNodeCopyResponse")
    public JAXBElement<SimpleResponseType> createNodeToNodeCopyResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_NodeToNodeCopyResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "RerunTestResponse")
    public JAXBElement<ObjectCreateResponseType> createRerunTestResponse(ObjectCreateResponseType value) {
        return new JAXBElement<ObjectCreateResponseType>(_RerunTestResponse_QNAME, ObjectCreateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TestListResponse")
    public JAXBElement<ObjectListResponseType> createTestListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TestListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectCreateResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointDeliveryEventResponse")
    public JAXBElement<ObjectCreateResponseType> createTouchpointDeliveryEventResponse(ObjectCreateResponseType value) {
        return new JAXBElement<ObjectCreateResponseType>(_TouchpointDeliveryEventResponse_QNAME, ObjectCreateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointProductionJobListResponse")
    public JAXBElement<ObjectListResponseType> createTouchpointProductionJobListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TouchpointProductionJobListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointListResponse")
    public JAXBElement<ObjectListResponseType> createTouchpointListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TouchpointListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataResourceListResponse")
    public JAXBElement<ObjectListResponseType> createDataResourceListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_DataResourceListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointCollectionListResponse")
    public JAXBElement<ObjectListResponseType> createTouchpointCollectionListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TouchpointCollectionListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointImportResponse")
    public JAXBElement<BackgroundTaskIdentificationResponseType> createTouchpointImportResponse(BackgroundTaskIdentificationResponseType value) {
        return new JAXBElement<BackgroundTaskIdentificationResponseType>(_TouchpointImportResponse_QNAME, BackgroundTaskIdentificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointCloneResponse")
    public JAXBElement<BackgroundTaskIdentificationResponseType> createTouchpointCloneResponse(BackgroundTaskIdentificationResponseType value) {
        return new JAXBElement<BackgroundTaskIdentificationResponseType>(_TouchpointCloneResponse_QNAME, BackgroundTaskIdentificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TouchpointExportResponse")
    public JAXBElement<BackgroundTaskIdentificationResponseType> createTouchpointExportResponse(BackgroundTaskIdentificationResponseType value) {
        return new JAXBElement<BackgroundTaskIdentificationResponseType>(_TouchpointExportResponse_QNAME, BackgroundTaskIdentificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "DataSourceListResponse")
    public JAXBElement<ObjectListResponseType> createDataSourceListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_DataSourceListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateConnectedOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateConnectedOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CreateConnectedOrderResponse")
    public JAXBElement<CreateConnectedOrderResponseType> createCreateConnectedOrderResponse(CreateConnectedOrderResponseType value) {
        return new JAXBElement<CreateConnectedOrderResponseType>(_CreateConnectedOrderResponse_QNAME, CreateConnectedOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloneConnectedOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CloneConnectedOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "CloneConnectedOrderResponse")
    public JAXBElement<CloneConnectedOrderResponseType> createCloneConnectedOrderResponse(CloneConnectedOrderResponseType value) {
        return new JAXBElement<CloneConnectedOrderResponseType>(_CloneConnectedOrderResponse_QNAME, CloneConnectedOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "RemoveConnectedOrderResponse")
    public JAXBElement<SimpleResponseType> createRemoveConnectedOrderResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_RemoveConnectedOrderResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ReleaseForApprovalOrActivateConnectedOrderResponse")
    public JAXBElement<SimpleResponseType> createReleaseForApprovalOrActivateConnectedOrderResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_ReleaseForApprovalOrActivateConnectedOrderResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ApproveConnectedOrderResponse")
    public JAXBElement<SimpleResponseType> createApproveConnectedOrderResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_ApproveConnectedOrderResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "InitiateConnectedOrderDeliveryResponse")
    public JAXBElement<SimpleResponseType> createInitiateConnectedOrderDeliveryResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_InitiateConnectedOrderDeliveryResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ConnectedOrderListResponse")
    public JAXBElement<ObjectListResponseType> createConnectedOrderListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_ConnectedOrderListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ProjectListResponse")
    public JAXBElement<ObjectListResponseType> createProjectListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_ProjectListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FileResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "ProjectAuditReportResponse")
    public JAXBElement<FileResponseType> createProjectAuditReportResponse(FileResponseType value) {
        return new JAXBElement<FileResponseType>(_ProjectAuditReportResponse_QNAME, FileResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobStatusResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobStatusResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "JobStatusResponse")
    public JAXBElement<JobStatusResponseType> createJobStatusResponse(JobStatusResponseType value) {
        return new JAXBElement<JobStatusResponseType>(_JobStatusResponse_QNAME, JobStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "EditTaskResponse")
    public JAXBElement<SimpleResponseType> createEditTaskResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_EditTaskResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "RemoveTaskResponse")
    public JAXBElement<SimpleResponseType> createRemoveTaskResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_RemoveTaskResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "TaskListResponse")
    public JAXBElement<ObjectListResponseType> createTaskListResponse(ObjectListResponseType value) {
        return new JAXBElement<ObjectListResponseType>(_TaskListResponse_QNAME, ObjectListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BackgroundTaskIdentificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "JobPerformanceReportResponse")
    public JAXBElement<BackgroundTaskIdentificationResponseType> createJobPerformanceReportResponse(BackgroundTaskIdentificationResponseType value) {
        return new JAXBElement<BackgroundTaskIdentificationResponseType>(_JobPerformanceReportResponse_QNAME, BackgroundTaskIdentificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "EditTestResponse")
    public JAXBElement<SimpleResponseType> createEditTestResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_EditTestResponse_QNAME, SimpleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://messagepoint.com/api/schemas", name = "RemoveTestResponse")
    public JAXBElement<SimpleResponseType> createRemoveTestResponse(SimpleResponseType value) {
        return new JAXBElement<SimpleResponseType>(_RemoveTestResponse_QNAME, SimpleResponseType.class, null, value);
    }

}
