//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectListResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectListResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="FailureResponse" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="ObjectList" type="{http://messagepoint.com/api/schemas}ObjectListType"/&gt;
 *           &lt;element name="TouchpointList" type="{http://messagepoint.com/api/schemas}TouchpointListType"/&gt;
 *           &lt;element name="ConnectedOrderList" type="{http://messagepoint.com/api/schemas}ConnectedOrderListType"/&gt;
 *           &lt;element name="DataSourceList" type="{http://messagepoint.com/api/schemas}DataSourceListType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectListResponseType", propOrder = {
    "failureResponse",
    "objectList",
    "touchpointList",
    "connectedOrderList",
    "dataSourceList"
})
public class ObjectListResponseType {

    @XmlElement(name = "FailureResponse", namespace = "http://messagepoint.com/api/schemas")
    protected String failureResponse;
    @XmlElement(name = "ObjectList", namespace = "http://messagepoint.com/api/schemas")
    protected ObjectListType objectList;
    @XmlElement(name = "TouchpointList", namespace = "http://messagepoint.com/api/schemas")
    protected TouchpointListType touchpointList;
    @XmlElement(name = "ConnectedOrderList")
    protected ConnectedOrderListType connectedOrderList;
    @XmlElement(name = "DataSourceList")
    protected DataSourceListType dataSourceList;

    /**
     * Gets the value of the failureResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureResponse() {
        return failureResponse;
    }

    /**
     * Sets the value of the failureResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureResponse(String value) {
        this.failureResponse = value;
    }

    /**
     * Gets the value of the objectList property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectListType }
     *     
     */
    public ObjectListType getObjectList() {
        return objectList;
    }

    /**
     * Sets the value of the objectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectListType }
     *     
     */
    public void setObjectList(ObjectListType value) {
        this.objectList = value;
    }

    /**
     * Gets the value of the touchpointList property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointListType }
     *     
     */
    public TouchpointListType getTouchpointList() {
        return touchpointList;
    }

    /**
     * Sets the value of the touchpointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointListType }
     *     
     */
    public void setTouchpointList(TouchpointListType value) {
        this.touchpointList = value;
    }

    /**
     * Gets the value of the connectedOrderList property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectedOrderListType }
     *     
     */
    public ConnectedOrderListType getConnectedOrderList() {
        return connectedOrderList;
    }

    /**
     * Sets the value of the connectedOrderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectedOrderListType }
     *     
     */
    public void setConnectedOrderList(ConnectedOrderListType value) {
        this.connectedOrderList = value;
    }

    /**
     * Gets the value of the dataSourceList property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceListType }
     *     
     */
    public DataSourceListType getDataSourceList() {
        return dataSourceList;
    }

    /**
     * Sets the value of the dataSourceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceListType }
     *     
     */
    public void setDataSourceList(DataSourceListType value) {
        this.dataSourceList = value;
    }

}
