//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceDataFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceDataFileType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ReferenceDataSourceName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="ReferenceDataFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceDataFileType", propOrder = {
    "referenceDataSourceName",
    "referenceDataFileName"
})
public class ReferenceDataFileType {

    @XmlElement(name = "ReferenceDataSourceName")
    protected String referenceDataSourceName;
    @XmlElement(name = "ReferenceDataFileName")
    protected String referenceDataFileName;

    /**
     * Gets the value of the referenceDataSourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDataSourceName() {
        return referenceDataSourceName;
    }

    /**
     * Sets the value of the referenceDataSourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDataSourceName(String value) {
        this.referenceDataSourceName = value;
    }

    /**
     * Gets the value of the referenceDataFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDataFileName() {
        return referenceDataFileName;
    }

    /**
     * Sets the value of the referenceDataFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDataFileName(String value) {
        this.referenceDataFileName = value;
    }

}
