//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="folder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="metatags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="globalContent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="VariableContentEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ActivateTarget" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "folder",
    "metatags",
    "globalContent",
    "variableContentEnabled",
    "activateTarget"
})
@XmlRootElement(name = "SFTPRepoSyncRequest")
public class SFTPRepoSyncRequest
    extends ClientIdentificationType
{

    @XmlElement(required = true)
    protected String folder;
    protected String metatags;
    protected Boolean globalContent;
    @XmlElement(name = "VariableContentEnabled")
    protected Boolean variableContentEnabled;
    @XmlElement(name = "ActivateTarget")
    protected Boolean activateTarget;

    /**
     * Gets the value of the folder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolder() {
        return folder;
    }

    /**
     * Sets the value of the folder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolder(String value) {
        this.folder = value;
    }

    /**
     * Gets the value of the metatags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetatags() {
        return metatags;
    }

    /**
     * Sets the value of the metatags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetatags(String value) {
        this.metatags = value;
    }

    /**
     * Gets the value of the globalContent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGlobalContent() {
        return globalContent;
    }

    /**
     * Sets the value of the globalContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlobalContent(Boolean value) {
        this.globalContent = value;
    }

    /**
     * Gets the value of the variableContentEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVariableContentEnabled() {
        return variableContentEnabled;
    }

    /**
     * Sets the value of the variableContentEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVariableContentEnabled(Boolean value) {
        this.variableContentEnabled = value;
    }

    /**
     * Gets the value of the activateTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActivateTarget() {
        return activateTarget;
    }

    /**
     * Sets the value of the activateTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActivateTarget(Boolean value) {
        this.activateTarget = value;
    }

}
