//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType"/&gt;
 *         &lt;element name="SearchString" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Advanced" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "touchpoint",
    "searchString",
    "advanced"
})
@XmlRootElement(name = "TargetingGroupsSearchRequest")
public class TargetingGroupsSearchRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "Touchpoint", required = true)
    protected TouchpointType touchpoint;
    @XmlElement(name = "SearchString", required = true)
    protected String searchString;
    @XmlElement(name = "Advanced")
    protected boolean advanced;

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

    /**
     * Gets the value of the searchString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchString() {
        return searchString;
    }

    /**
     * Sets the value of the searchString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchString(String value) {
        this.searchString = value;
    }

    /**
     * Gets the value of the advanced property.
     * 
     */
    public boolean isAdvanced() {
        return advanced;
    }

    /**
     * Sets the value of the advanced property.
     * 
     */
    public void setAdvanced(boolean value) {
        this.advanced = value;
    }

}
