//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ModelGuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="ExtensionType" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="Touchpoint" type="{http://messagepoint.com/api/schemas}TouchpointType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelGuid",
    "type",
    "extensionType",
    "touchpoint"
})
@XmlRootElement(name = "TouchpointExportRequest")
public class TouchpointExportRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "ModelGuid")
    protected String modelGuid;
    @XmlElement(name = "Type")
    @XmlSchemaType(name = "unsignedInt")
    protected long type;
    @XmlElement(name = "ExtensionType")
    @XmlSchemaType(name = "unsignedInt")
    protected long extensionType;
    @XmlElement(name = "Touchpoint")
    protected TouchpointType touchpoint;

    /**
     * Gets the value of the modelGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelGuid() {
        return modelGuid;
    }

    /**
     * Sets the value of the modelGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelGuid(String value) {
        this.modelGuid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public long getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(long value) {
        this.type = value;
    }

    /**
     * Gets the value of the extensionType property.
     * 
     */
    public long getExtensionType() {
        return extensionType;
    }

    /**
     * Sets the value of the extensionType property.
     * 
     */
    public void setExtensionType(long value) {
        this.extensionType = value;
    }

    /**
     * Gets the value of the touchpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TouchpointType }
     *     
     */
    public TouchpointType getTouchpoint() {
        return touchpoint;
    }

    /**
     * Sets the value of the touchpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TouchpointType }
     *     
     */
    public void setTouchpoint(TouchpointType value) {
        this.touchpoint = value;
    }

}
