//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="outputType" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="includePincLicenseStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outputType",
    "includePincLicenseStatus"
})
@XmlRootElement(name = "UnifiedLoginReportRequest")
public class UnifiedLoginReportRequest
    extends ClientIdentificationType
{

    @XmlSchemaType(name = "unsignedInt")
    protected long outputType;
    protected Boolean includePincLicenseStatus;

    /**
     * Gets the value of the outputType property.
     * 
     */
    public long getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     */
    public void setOutputType(long value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the includePincLicenseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludePincLicenseStatus() {
        return includePincLicenseStatus;
    }

    /**
     * Sets the value of the includePincLicenseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludePincLicenseStatus(Boolean value) {
        this.includePincLicenseStatus = value;
    }

}
