//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 07:56:45 PM IST 
//


package com.ccp.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://messagepoint.com/api/schemas}ClientIdentificationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PodId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="JobId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ChunkNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="Base64Content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="JobKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CheckSum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FileSize" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podId",
    "jobId",
    "type",
    "chunkNumber",
    "base64Content",
    "jobKey",
    "checkSum",
    "fileSize",
    "returnCode"
})
@XmlRootElement(name = "UploadProcessedJobRequest")
public class UploadProcessedJobRequest
    extends ClientIdentificationType
{

    @XmlElement(name = "PodId")
    protected String podId;
    @XmlElement(name = "JobId", required = true)
    protected String jobId;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "ChunkNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected long chunkNumber;
    @XmlElement(name = "Base64Content", required = true)
    protected String base64Content;
    @XmlElement(name = "JobKey")
    protected String jobKey;
    @XmlElement(name = "CheckSum")
    protected String checkSum;
    @XmlElement(name = "FileSize")
    @XmlSchemaType(name = "unsignedInt")
    protected Long fileSize;
    @XmlElement(name = "ReturnCode")
    @XmlSchemaType(name = "unsignedInt")
    protected Long returnCode;

    /**
     * Gets the value of the podId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodId() {
        return podId;
    }

    /**
     * Sets the value of the podId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodId(String value) {
        this.podId = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobId(String value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the chunkNumber property.
     * 
     */
    public long getChunkNumber() {
        return chunkNumber;
    }

    /**
     * Sets the value of the chunkNumber property.
     * 
     */
    public void setChunkNumber(long value) {
        this.chunkNumber = value;
    }

    /**
     * Gets the value of the base64Content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64Content() {
        return base64Content;
    }

    /**
     * Sets the value of the base64Content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64Content(String value) {
        this.base64Content = value;
    }

    /**
     * Gets the value of the jobKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobKey() {
        return jobKey;
    }

    /**
     * Sets the value of the jobKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobKey(String value) {
        this.jobKey = value;
    }

    /**
     * Gets the value of the checkSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckSum() {
        return checkSum;
    }

    /**
     * Sets the value of the checkSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckSum(String value) {
        this.checkSum = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFileSize(Long value) {
        this.fileSize = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReturnCode(Long value) {
        this.returnCode = value;
    }

}
